### PR TITLE
Add MusicApp-KMP to samples

### PR DESCRIPTION
**Pull request by SEAbdulbasit**
I wanted to add Music App (https://github.com/SEAbdulbasit/MusicApp-KMP) to the samples list. This app demonstrates how to use native APIs in KMP. It retrieves the top 50-chart list from Spotify API and utilizes native APIs to load music from Spotify APIs. Ktor is used for network calling and Decompose for navigation. It supports Android, iOS, Web, and Desktop platforms.

### CODE REVIEW

**Comment by SebastianAigner** [comment]
Hi! Unfortunately, your project doesn't build on my machine:
```
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:3:8 Unresolved reference: uk
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:4:8 Unresolved reference: uk
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:5:8 Unresolved reference: uk
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:6:8 Unresolved reference: uk
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:7:8 Unresolved reference: uk
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:11:30 Unresolved reference: MediaPlayer
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:15:9 Unresolved reference: NativeDiscovery
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:20:17 Unresolved reference: CallbackMediaPlayerComponent
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:22:17 Unresolved reference: EmbeddedMediaPlayerComponent
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:25:69 Unresolved reference: MediaPlayerEventAdapter
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:26:13 'mediaPlayerReady' overrides nothing
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:26:56 Unresolved reference: MediaPlayer
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:27:23 Unresolved reference: mediaPlayerReady
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:31:13 'finished' overrides nothing
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:31:48 Unresolved reference: MediaPlayer
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:32:23 Unresolved reference: finished
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:36:13 'error' overrides nothing
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:36:45 Unresolved reference: MediaPlayer
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:37:23 Unresolved reference: error
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:81:36 Unresolved reference: MediaPlayer
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:83:16 Unresolved reference: CallbackMediaPlayerComponent
e: file:///Users/Sebastian.Aigner/Desktop/github/MusicApp-KMP/shared/src/desktopMain/kotlin/com/example/musicapp_kmp/player/MediaPlayerController.kt:84:16 Unresolved reference: EmbeddedMediaPlayerComponent

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':shared:compileKotlinDesktop'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
```

Also, it's important for sample projects to work without users having to set up some external API keys, so it would be great if you could make sure that your app can display / work at least with some mock data / reduced functionality even when no API keys are set up.

**Review by SebastianAigner — CHANGES_REQUESTED** [review]
See comment in PR.

**Comment by SEAbdulbasit** [comment]
I will try to add Google login so that there is no need for API token.

**Comment by SEAbdulbasit** [comment]
Hi @SebastianAigner 👋 

I have made some updates, like applying the default hierarchy template and fixing the dependency issue. 

Currently, I have also included a sample response so that it can be run without any API keys. 

You can now view the live version at this link: https://seabdulbasit.github.io/MusicApp-KMP/. Please share your thoughts.

**Comment by SebastianAigner** [comment]
Hi @SEAbdulbasit, magnificent effort, and awesome to see you targeting the web as well! 🔥 I'm currently taking a vacation, but when I'm back, I'll be happily taking a look at the current version of the project.

**Comment by SEAbdulbasit** [comment]
Hi @SebastianAigner, are you back?

**Comment by SebastianAigner** [comment]
@SEAbdulbasit thanks for the ping again, will take a look when I have a free minute (as you can imagine, time is a rare commodity in the weeks before KotlinConf 😉)

**Comment by SEAbdulbasit** [comment]
Hi @SebastianAigner, 

I hope you had a fantastic time at KotlinConf. 

Can you take a look?

**Comment by SEAbdulbasit** [comment]
Hi @SebastianAigner 
Can you have a look kindly?

**Comment by SebastianAigner** [comment]
Thanks, this looks fine to me.

I'd encourage you to take a look at some of the warnings during compilation still, make sure that you're compatible with the latest versions of Compose and Kotlin Multiplatform too. Please also make sure you're not overusing expect-actual classes (see here: https://kotlinlang.org/docs/multiplatform-expect-actual.html#expected-and-actual-classes) – instead, use expect/actual factory functions that return objects implementing a common interface on each platform.

I'm also getting a runtime error trying to run the web target, please also fix that:
Screenshot 2024-07-01 at 10 27 55

**Review by SebastianAigner — APPROVED** [review]

**Comment by SEAbdulbasit** [comment]
@pahill can you check again? I can see changes in only 1 file.

**Comment by pahill** [comment]
I see, I got confused with the force push.

**Comment by SEAbdulbasit** [comment]
@pahill @SebastianAigner can you take a look? 
Unable to merge the PR because it needs approval from `kotlin-multiplatform-technical-writing`I think.

**Comment by SEAbdulbasit** [comment]
@SebastianAigner can you have a look?

**Review by zamulla — APPROVED** [review]
👍

**Pull request merged**
