### PR TITLE
feat: add Twine to multiplatform-samples

### PR DESCRIPTION
**Pull request by msasikanth**
Hello, I have built a Kotlin and Compose Multiplatform RSS Reader called Twine, that showcases a nice UI/UX. Along with showcasing building nice UI components (custom and extending Material) in Compose Multiplatform, this also showcases topics like DI, Networking and Caching, and writing common code that extends platform-specific APIs. It also includes a few tests for testing the parsers.

If this is a good sample for people, please include it in the doc, or else feel free to close the PR.

Here is the repo to check out the implementation: https://github.com/msasikanth/twine

### CODE REVIEW

**Comment by SebastianAigner** [comment]
Hi folks, the app looks nice, but in order to be an example that we can recommend to the community, it’s currently not working well enough on iOS. I’ve installed the app and ran into some issues with crashes and non-working reader functionality right out of the gate. I’ve reported two of them in the repo, but I recommend testing your app a bit more thoroughly overall to make sure it‘s a great experience for users trying it out. Once that is done, I think we can revisit adding the app! It looks really great, it just needs the stability and well working basic functionality to back it up! 😁

**Comment by msasikanth** [comment]
@SebastianAigner I have addressed the issues you have raised, I think the app is stable now in terms of usability. Do you want to wait until these changes are available in the stores in a new release, or you can revisit adding it to the samples page now? 👀

**Comment by SebastianAigner** [comment]
Hi @msasikanth -- because I assume a bunch of people will first try the app from the app stores before taking a look at the source code, I think it'd be best to wait until the changes are in the released store versions. Once that's done, from my end I'm happy to have this added to the example applications.

**Comment by msasikanth** [comment]
> Hi @msasikanth -- because I assume a bunch of people will first try the app from the app stores before taking a look at the source code, I think it'd be best to wait until the changes are in the released store versions. Once that's done, from my end I'm happy to have this added to the example applications.

Yep, the update is already available on Android and it's under review on iOS. Will ping once that's available as well 👍🏾

**Comment by msasikanth** [comment]
@SebastianAigner update is available on both the platforms now.

**Comment by SebastianAigner** [comment]
Looks good on my end. Thanks for making these changes! No objections from my end to adding this to the list. @JetBrains/kotlin-technical-writing?

**Review by SebastianAigner — APPROVED** [review]

**Comment by msasikanth** [comment]
@koshachy just checking in on this PR status.

**Review by zamulla — APPROVED** [review]
Thanks for submitting your app! We hope you will continue to develop it and showcase the Kotlin and Compose Multiplatform.

**Pull request merged**
