### PR TITLE
Update multiplatform-samples.md

### PR DESCRIPTION
**Pull request by razaghimahdi**
Added new sample, https://github.com/razaghimahdi/Shopping-By-KMP  This is a cross-platform application that is built using Jetpack Compose Multiplatform, a declarative framework for sharing UIs across multiple platforms with Kotlin. The application allows users to browse, search, and purchase products from a shopping catalog on Android, iOS.

### CODE REVIEW

**Comment by razaghimahdi** [comment]
update: now working on writing tests by kotest, Turbine, Fake data and Mockk and it would be pushed soon

**Comment by razaghimahdi** [comment]
also I added coil3 as image loader(not pushed yet)

**Comment by pahill** [comment]
Hi - I see you have a features list with some outstanding features. Perhaps you could finish those first before asking to be featured? cc @danil-pavlov

**Comment by razaghimahdi** [comment]
Hi there - Since this project is massive and complex, it would takes time to get full ready! but still important features has been implemented and some of new featured would be add in couple days. as u can see purpose of this sample is to show what compose multi-platform capable of to use in complex project. I hope u consider it as a helpful sample!

**Comment by razaghimahdi** [comment]
Hello, I hope you all doing well; I'm commenting again to see if there is any question or any action need, for now I'm trying to add more features to improve it as a production level, fixing bugs and writing test.
Thank you for your time. @pahill @zamulla

**Comment by pahill** [comment]
Hi, @SebastianAigner volunteered to review samples from now on. Thanks, Seb :)

**Comment by SebastianAigner** [comment]
Heya, the project in its current state doesn't build on my machine.

```
> Task :xcodeVersion UP-TO-DATE
> Task :shared:checkKotlinGradlePluginConfigurationErrors
> Task :shared:compileKotlinIosSimulatorArm64 FAILED
/Users/Sebastian.Aigner/Desktop/github/Shopping-By-KMP/shared/src/commonMain/kotlin/presentation/navigation/SearchNavigation.kt:3:21: error: Unresolved reference: util
/Users/Sebastian.Aigner/Desktop/github/Shopping-By-KMP/shared/src/commonMain/kotlin/presentation/ui/main/home/view_model/HomeViewModel.kt:28:21: error: Unresolved reference: util
error: Compilation finished with errors
Compilation finished with errors
```

**Comment by SebastianAigner** [comment]
Also, it's important for sample projects to work without users having to set up some external API keys, so it would be great if you could make sure that your app can display / work at least with some mock data / reduced functionality even when no API keys are set up.

**Review by SebastianAigner — CHANGES_REQUESTED** [review]
See points mentioned above.

**Comment by razaghimahdi** [comment]
> Heya, the project in its current state doesn't build on my machine.
> 
> ```
> > Task :xcodeVersion UP-TO-DATE
> > Task :shared:checkKotlinGradlePluginConfigurationErrors
> > Task :shared:compileKotlinIosSimulatorArm64 FAILED
> /Users/Sebastian.Aigner/Desktop/github/Shopping-By-KMP/shared/src/commonMain/kotlin/presentation/navigation/SearchNavigation.kt:3:21: error: Unresolved reference: util
> /Users/Sebastian.Aigner/Desktop/github/Shopping-By-KMP/shared/src/commonMain/kotlin/presentation/ui/main/home/view_model/HomeViewModel.kt:28:21: error: Unresolved reference: util
> error: Compilation finished with errors
> Compilation finished with errors
> ```

Hi there, my mistake while pushing :) now it's fixed

**Comment by razaghimahdi** [comment]
> Also, it's important for sample projects to work without users having to set up some external API keys, so it would be great if you could make sure that your app can display / work at least with some mock data / reduced functionality even when no API keys are set up.

Good point, actually there is no api key. so user can easily use the app and everything display perfectly.

**Review by razaghimahdi — COMMENTED** [review]
reviewed

**Comment by razaghimahdi** [comment]
Hi there, 
So couple days ago, you mentioned that it would be better to have some mock data and stuff, so in the last update which I pushed an hour ago, many screens added with mock data. 
I hope this sample be useful for CMP community.
Thanks for your time. @SebastianAigner

**Comment by SebastianAigner** [comment]
Hey @razaghimahdi , I see a few obvious quality issues with the app in its current state that would need to be addressed before we can consider the project as a sample.

The app frequently freezes for 30+ frames, see here:
Screenshot 2024-01-30 at 14 01 00

There are also a large number of warnings in the project that should be addressed. 
Screenshot 2024-01-30 at 14 04 46

You can find these points via the "Inspect code" intention in Android Studio:
Screenshot 2024-01-30 at 14 06 55

In large parts, your code also seems to not follow the formatting conventions.

**Comment by razaghimahdi** [comment]
Hi @SebastianAigner , thanks for your time, I did some changes. 
About skipping frame, I did some improvements but I believe main reason of this message is because of you are on debugging and emulator. Also I did some clean up code but still there are some unused code, like colors and other thing that could be useful in future.

**Comment by razaghimahdi** [comment]
Hi @SebastianAigner , I hope you doing well. In last update, I added proguard and R8 to have a better performance since you mentioned about skipping frame. [apk with enabled R8](https://github.com/razaghimahdi/Shopping-By-KMP/blob/master/androidApp/release/androidApp-release.apk)
```

    buildTypes {
        release {
            isMinifyEnabled = false // as default is false
            isShrinkResources = false // as default is false

            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
```

**Comment by SebastianAigner** [comment]
Hi @razaghimahdi, thanks for the updates. I'm off right now, but I'll take a look sometime next week.

**Comment by SebastianAigner** [comment]
Hi @razaghimahdi,

Unforunately, your project fails to compile for iOS:

```
SwiftDriverJobDiscovery normal arm64 Compiling iOSApp.swift (in target 'iosApp' from project 'iosApp')

** BUILD FAILED **


The following build commands failed:
	SwiftCompile normal arm64 /Users/Sebastian.Aigner/Desktop/github/clean/Shopping-By-KMP/iosApp/iosApp/ContentView.swift (in target 'iosApp' from project 'iosApp')
	SwiftCompile normal arm64 Compiling\ ContentView.swift /Users/Sebastian.Aigner/Desktop/github/clean/Shopping-By-KMP/iosApp/iosApp/ContentView.swift (in target 'iosApp' from project 'iosApp')
(2 failures)
```

**Review by SebastianAigner — CHANGES_REQUESTED** [review]
Fails to compile for iOS.

**Comment by razaghimahdi** [comment]
@SebastianAigner Hi man, I hope you doing well, please check out lsat update which is uploaded just now.

**Review by SebastianAigner — APPROVED** [review]
Thanks for the changes @razaghimahdi, the project builds fine now. Performance is also significantly improved since the last time I checked 🎉 

@JetBrains/kotlin-technical-writing / @zamulla , please take a look at the actual diff that changes the docs in this PR (I have not checked it), and then you can move forward on your own volition – LGTM. :)

**Comment by razaghimahdi** [comment]
@SebastianAigner Oh man that is good to hear, first let me say thank you for your time. 
Also this is not all, this sample gonna have more feature and updates in soon to show what compose multiplatform capable of. 
Again thank you for your time and consideration.

**Comment by razaghimahdi** [comment]
@zamulla Hi there, I hope you doing well. I'm just checking if is there any change need.
Thanks for your time.

**Comment by razaghimahdi** [comment]
@zamulla

**Comment by razaghimahdi** [comment]
@zamulla So in last update of this sample, I updated to compose multiplatform 1.6.0 base on [your last article](https://blog.jetbrains.com/kotlin/2024/02/compose-multiplatform-1-6-0-release/) added some simple UI test, But it will be more soon, Also started to use Common resources API. 
Anyway if there is any change need please let me know

**Comment by razaghimahdi** [comment]
@zamulla

**Comment by razaghimahdi** [comment]
Updates: 
- compose navigation added
- compose multiplatform updated to 1.6.10-beta02

**Comment by razaghimahdi** [comment]
Hi @zamulla , it's been almost 2 month since @SebastianAigner approved. I just wanted to check out if there is any update needs. thanks again for your time

**Review by zamulla — APPROVED** [review]
Sorry, I missed the tag here. Looks good, thanks a lot!

**Pull request merged**
